/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SchemaDependencies {
  /**
   * An array of the Cran packages required for the custom R visual script to operate
   */
  cranPackages?: CranPackage[];
  [k: string]: any;
}
/**
 * cranPackage - Defines the name and displayName of a required Cran package
 */
export interface CranPackage {
  /**
   * The name for this Cran package
   */
  name: string;
  /**
   * The name for this Cran package that is shown to the user
   */
  displayName?: string;
  /**
   * A url for package documentation in Cran website
   */
  url: string;
}
